feature:  READMEの追加
hitomi-t260g/solve-javascript-questions pull request #3
Opened 2022-08-20 10:16 UTC by t-keshi

# 変更点

READMEを追加しました

2022-08-20 16:19 UTC, hitomi-t260g commented
Files changedタブより確認したところ、内容に問題ある記述がないと判断したため、マージいたします。

2022-08-20 16:24 UTC, hitomi-t260g requested changes
レビュー練習です。よろしくお願いいたします。

2022-08-20 16:24 UTC, hitomi-t260g commented on README.md
> +# solve-javascript-questions.git
「This is repository, created to solve https://github.com/lydiahallie/javascript-questions/blob/master/ja-JA/README-ja_JA.md.」に修正願います。

2022-08-20 16:25 UTC, hitomi-t260g commented
と思ったのですが、レビュー機能を使うのが本筋かと思ったので、やはり修正依頼を出してみました。

2022-08-21 02:11 UTC, t-keshi commented on README.md
> +# solve-javascript-questions.git
@hitomi-t260g 

修正しました！
ご指摘ありがとうございます。

2022-08-21 20:32 UTC, hitomi-t260g commented
@t-keshi 
内容に問題がないと判断したため、マージいたします。

2022-08-21 20:32 UTC, merged